# Generated by Django 5.1.1 on 2024-10-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafeadminend", "0003_alter_notification_options_alter_notification_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="user",
            new_name="recipient",
        ),
    ]
