# Generated by Django 5.1.1 on 2024-10-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafeadminend", "0004_rename_user_notification_recipient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="recipient",
            new_name="user",
        ),
    ]
