# Generated by Django 5.1.1 on 2024-10-09 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafeadminend", "0005_rename_recipient_notification_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RedemptionOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points_required", models.PositiveIntegerField()),
                ("description", models.TextField()),
                (
                    "fooditem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redeem",
                        to="cafeadminend.fooditem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RedemptionTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points_redeemed", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("DELIVERED", "Delivered")],
                        default="PENDING",
                        max_length=250,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "redemption_option",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cafeadminend.redemptionoption",
                    ),
                ),
            ],
        ),
    ]
