# Generated by Django 5.1.1 on 2024-10-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customerend", "0005_customerloyaltypoint_redemptionoption_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redemptiontransaction",
            name="redemption_option",
        ),
        migrations.RemoveField(
            model_name="redemptiontransaction",
            name="customer",
        ),
        migrations.DeleteModel(
            name="RedemptionOption",
        ),
        migrations.DeleteModel(
            name="RedemptionTransaction",
        ),
    ]
