# Generated by Django 5.1.1 on 2024-10-14 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("menu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "estimated_time",
                    models.IntegerField(
                        choices=[
                            (5, "5 minutes"),
                            (10, "10 minutes"),
                            (15, "15 minutes"),
                            (20, "20 minutes"),
                            (25, "25 minutes"),
                            (30, "30 minutes"),
                            (35, "35 minutes"),
                            (40, "40 minutes"),
                            (45, "45 minutes"),
                            (50, "50 minutes"),
                            (55, "55 minutes"),
                            (60, "60 minutes"),
                        ],
                        default=5,
                        verbose_name="Estimated Delivery Time",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETE", "Complete"),
                            ("PENDING", "Pending"),
                            ("READY", "Ready for delivery"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="PENDING",
                        max_length=250,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dining_table",
                    models.ForeignKey(
                        blank=True,
                        max_length=250,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.diningtable",
                    ),
                ),
                ("order_items", models.ManyToManyField(to="cart.cartitem")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Orders",
                "ordering": ["-updated_at"],
            },
        ),
    ]
